apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  name: activiti-pgsql-claim # Sets name of PV
  namespace: activiti
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce # Sets read and write access
  resources:
    requests:
      storage: 50Gi # Sets volume sizee's path
