apiVersion: apps/v1
kind: Deployment
metadata:
  name: activiti-connector-service
  namespace: activiti
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activiti-connector-service
  template:
    metadata:
      labels:
        app: activiti-connector-service
    spec:
      containers:
        - name: activiti-connector-service
          image: unamanic/activiti-connector-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
            limits:
              memory: "1024Mi"
          env:
            - name: SPRING_RABBITMQ_HOST
              value: activiti-rabbit
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: activiti-rabbit-default-user
                  key: username
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: activiti-rabbit-default-user
                  key: password

      imagePullSecrets:
        - name: regcred
