apiVersion: apps/v1
kind: Deployment
metadata:
  name: activiti-modeler-backend
  namespace: activiti
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activiti-modeler-backend
  template:
    metadata:
      labels:
        app: activiti-modeler-backend
    spec:
      containers:
        - name: activiti-modeler-backend
          image: unamanic/activiti-modeler-backend
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
            limits:
              memory: "1024Mi"
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://activiti-pgsql-postgresql:5432/activiti_db
            - name: SPRING_DATASOURCE_USERNAME
              value: activiti
            - name: SPRING_DATASOURCE_HIKARI_SCHEMA
              value: modeler
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: activiti-pgsql-postgresql
                  key: password
            - name: ACT_KEYCLOAK_URL
              value: http://keycloak.internal.witt-family.net
            - name: ACT_KEYCLOAK_REALM
              value: activiti
            - name: ACT_KEYCLOAK_RESOURCE
              value: activiti
            - name: ACT_KEYCLOAK_SSL_REQUIRED
              value: none
            - name: ACTIVITI_CLOUD_MODELING_URL
              value: http://modeler.internal.witt-family.net
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: /modeling-service
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: activiti-modeler-backend
  namespace: activiti
spec:
  type: LoadBalancer
  selector:
    app: activiti-modeler-backend
  ports:
    - port: 80
      targetPort: 8080
  loadBalancerIP: 10.0.10.161
