apiVersion: apps/v1
kind: Deployment
metadata:
  name: activiti-modeler-app
  namespace: activiti
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activiti-modeler-app
  template:
    metadata:
      labels:
        app: activiti-modeler-app
    spec:
      containers:
        - name: activiti-modeler-app
          image: unamanic/activiti-modeler-app
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
            limits:
              memory: "1024Mi"
          env:
            - name: APP_CONFIG_OAUTH2_HOST
              value: http://keycloak.internal.witt-family.net/realms/activiti
            - name: APP_CONFIG_OAUTH2_CLIENTID
              value: activiti
            - name: APP_CONFIG_BPM_HOST
              value: http://modeler-backend.internal.witt-family.net
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: activiti-modeler-app
  namespace: activiti
spec:
  type: LoadBalancer
  selector:
    app: activiti-modeler-app
  ports:
    - port: 80
      targetPort: 8080
  loadBalancerIP: 10.0.10.162
