apiVersion: v1
kind: Service
metadata:
  name: activiti-query-service
  namespace: activiti
spec:
  type: LoadBalancer
  selector:
    app: activiti-query-service
  ports:
    - port: 80
      targetPort: 8080
  loadBalancerIP: 10.0.10.160
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: activiti-query-service
  namespace: activiti
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activiti-query-service
  serviceName: activiti-query-service
  template:
    metadata:
      labels:
        app: activiti-query-service
    spec:
      volumes:
        - name: shared-data
      initContainers:
        - name: instance-ordinal
          image: busybox
          command: ["/bin/sh", "-c", 'printf "\nactiviti.cloud.messaging.instance-index=${HOSTNAME##*-}\n" > /deployments/config/ordinal.properties']
          volumeMounts:
            - mountPath: /deployments/config
              name: shared-data
      containers:
        - name: activiti-query-service
          image: unamanic/activiti-query-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
            limits:
              memory: "1024Mi"
          volumeMounts:
            - mountPath: /deployments/config
              name: shared-data
          env:
            - name: SPRING_CONFIG_LOCATION
              value: "classpath:/application.yaml,/deployments/config/ordinal.properties"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://activiti-pgsql-postgresql:5432/activiti_db
            - name: SPRING_DATASOURCE_USERNAME
              value: activiti
            - name: SPRING_DATASOURCE_HIKARI_SCHEMA
              value: query_service
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: activiti-pgsql-postgresql
                  key: password
            - name: SPRING_RABBITMQ_HOST
              value: activiti-rabbit
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: activiti-rabbit-default-user
                  key: username
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: activiti-rabbit-default-user
                  key: password
            - name: ACT_KEYCLOAK_URL
              value: http://keycloak.internal.witt-family.net
            - name: ACT_KEYCLOAK_REALM
              value: activiti
            - name: ACT_KEYCLOAK_RESOURCE
              value: activiti
            - name: ACT_KEYCLOAK_SSL_REQUIRED
              value: none
            - name: ACT_MESSAGING_PARTITIONED
              value: "true"
            - name: ACT_MESSAGING_PARTITION_COUNT
              value: "1"
      imagePullSecrets:
        - name: regcred


