apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: activiti-rabbit
  namespace: activiti
spec:
  replicas: 3
  resources:
    requests:
      cpu: 500m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  persistence:
    storageClassName: nfs-client
    storage: 5Gi # Sets volume sizee's path