version: 2
services:
  activiti-postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=activiti
      - POSTGRES_DB=activitidb
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

  keycloak:
    container_name: keycloak
    image: activiti/activiti-keycloak
    volumes:
      - ./activiti-realm.json:/opt/jboss/keycloak/activiti-realm.json
    restart: unless-stopped
    depends_on:
      - nginx

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
      - 61613:61613
    volumes:
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
    #      - rabbitmq-data:./rabbitmq-data
    restart: unless-stopped

  activiti-cloud-modeling:
    container_name: activiti-cloud-modeling
    image: activiti/activiti-modeling-app:7.9.0
    environment:
      # JAVA_OPTS: "-Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8000,suspend=n -noverify"
      APP_CONFIG_OAUTH2_HOST: "http://${DOCKER_IP}/auth/realms/${KEYCLOAK_REALM}"
      APP_CONFIG_OAUTH2_CLIENTID: "${KEYCLOAK_REALM}"
      API_URL: "http://${DOCKER_IP}"
      BASE_PATH: /modeling
      SERVER_PORT: 8080
      APP_CONFIG_BPM_HOST: "http://${DOCKER_IP}"
      APP_CONFIG_OAUTH2_REDIRECT_SILENT_IFRAME_URI: /modeling/assets/silent-refresh.html
      APP_CONFIG_OAUTH2_REDIRECT_LOGIN: /modeling
      APP_CONFIG_OAUTH2_REDIRECT_LOGOUT: /modeling
    restart: unless-stopped

  activiti-cloud-modeling-backend:
    container_name: activiti-cloud-modeling-backend
    image: activiti/activiti-cloud-modeling:7.9.0
    environment:
      JAVA_OPTS:                    -Xmx1024m -Xms512m -XX:+UnlockExperimentalVMOptions   -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
      SPRING_APPLICATION_NAME:      modeling-service
      SERVER_PORT:                  8080
      ACT_KEYCLOAK_URL:             http://${DOCKER_IP}/auth
      ACT_KEYCLOAK_REALM:           ${KEYCLOAK_REALM}
      ACT_KEYCLOAK_RESOURCE:        ${KEYCLOAK_RESOURCE}
      ACTIVITI_CLOUD_MODELING_URL:  localhost:8080
      SERVER_SERVLET_CONTEXT_PATH:  /modeling-service

volumes:
  rabbitmq-data:
  pgdata:

