spring.application.name: modeler
authorizations:
  security-constraints:
    - authRoles:
        - ${ACT_KEYCLOAK_MODELER_ROLE:ACTIVITI_MODELER}
      securityCollections:
        - patterns:
            - ${ACT_KEYCLOAK_PATTERNS:/v1/*}
    - securityCollections:
        - patterns:
            - /v1/identity/*