spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/activiti_db
    username: activiti
    password: "@WSX3edc$RFV5tgb"
    hikari:
      schema: query_service
  rabbitmq:
    username: default_user__A3swWy6z-ThqiPDg36
    password: 8_SEOpUR966TUmKUXPvle3rC6HGFYNtm
    host: localhost


